// GENERATED by scripts/i18n-barrels.mjs — do not edit by hand.
// Run `node scripts/i18n-barrels.mjs` (or `moon run web:i18n-barrels`) to refresh.
import auth from './auth.json';
import board from './board.json';
import common from './common.json';
import nav from './nav.json';
import settings from './settings.json';

export default {
  auth,
  board,
  common,
  nav,
  settings,
};
