'use client';

import { Suspense } from 'react';
import { PageHeader } from '@/components/page-header';
import { getDigests } from '@/lib/api';
import { useApiData } from '@/lib/use-api-data';
import { useGatewayErrorToast } from '@/lib/use-gateway-error-toast';
import { DigestsView } from './digests-view';

export default function DigestsPage() {
  const { data, error, loading } = useApiData(() => getDigests());
  useGatewayErrorToast(error);

  return (
    <>
      <PageHeader
        title="Digests"
        icon="Newspaper"
        description="Fleet digests — what shipped, what failed, and what needs attention over each window. Generated by the digest workflow."
      />
      <div className="reveal-staged container space-y-6 pb-8 pt-2">
        <Suspense fallback={null}>
          <DigestsView digests={data ?? []} loading={loading && !data} />
        </Suspense>
      </div>
    </>
  );
}
