// i18n catalog barrel generator (Phase 82 Theme A). The message catalogs are split
// per namespace (`messages/<locale>/<namespace>.json`) so parallel migration slices
// don't collide in one big file. This script regenerates the per-locale barrel
// `messages/<locale>/index.ts` that statically imports every namespace fragment and
// default-exports the merged tree — the runtime (`i18n/messages.ts`) imports the
// four barrels, so the whole catalog still bundles under `output: 'export'` with no
// request-time / dynamic catalog resolution.
//
//   node scripts/i18n-barrels.mjs           # regenerate every locale barrel
//   node scripts/i18n-barrels.mjs --check   # fail if any barrel is out of date (CI)
//
// A plain .mjs (node-only, no build) like the sibling validator/extractor. Run it
// after adding or removing a namespace fragment; `--check` guards it in CI.

import { readdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const MESSAGES_DIR = join(dirname(fileURLToPath(import.meta.url)), '..', 'packages', 'web', 'messages');

/** Locale sub-directories under messages/ (everything but the `meta` sidecar dir). */
export function localeDirs(messagesDir = MESSAGES_DIR) {
  return readdirSync(messagesDir, { withFileTypes: true })
    .filter((e) => e.isDirectory() && e.name !== 'meta')
    .map((e) => e.name)
    .sort();
}

/** The namespace fragment names (sans `.json`) present for a locale, sorted. */
function namespaces(localeDir) {
  return readdirSync(localeDir)
    .filter((f) => f.endsWith('.json'))
    .map((f) => f.replace(/\.json$/, ''))
    .sort();
}

/** A JS identifier for a namespace (namespaces are camelCase today, but be safe). */
function ident(ns) {
  return ns.replace(/[^a-zA-Z0-9_$]/g, '_');
}

/** Render the barrel source for one locale from its namespace fragments. */
export function renderBarrel(localeDir) {
  const ns = namespaces(localeDir);
  const header = [
    '// GENERATED by scripts/i18n-barrels.mjs — do not edit by hand.',
    '// Run `node scripts/i18n-barrels.mjs` (or `moon run web:i18n-barrels`) to refresh.',
    '',
  ];
  if (ns.length === 0) {
    // Intentionally-empty locale (de-DE / es-ES fall back to en-GB via the provider).
    return `${header.join('\n')}export default {};\n`;
  }
  const imports = ns.map((n) => `import ${ident(n)} from './${n}.json';`);
  const members = ns.map((n) => (ident(n) === n ? `  ${n},` : `  ${n}: ${ident(n)},`));
  return `${header.join('\n')}${imports.join('\n')}\n\nexport default {\n${members.join('\n')}\n};\n`;
}

function main() {
  const check = process.argv.includes('--check');
  let stale = 0;
  for (const locale of localeDirs()) {
    const localeDir = join(MESSAGES_DIR, locale);
    const barrelPath = join(localeDir, 'index.ts');
    const next = renderBarrel(localeDir);
    const current = existsSync(barrelPath) ? readFileSync(barrelPath, 'utf8') : null;
    if (current === next) continue;
    if (check) {
      stale += 1;
      console.error(`✖ barrel out of date: messages/${locale}/index.ts`);
    } else {
      writeFileSync(barrelPath, next);
      console.log(`wrote messages/${locale}/index.ts (${namespaces(localeDir).length} namespace(s))`);
    }
  }
  if (check) {
    if (stale > 0) {
      console.error(`\n✖ ${stale} barrel(s) out of date — run \`node scripts/i18n-barrels.mjs\` and commit.`);
      process.exit(1);
    }
    console.log('✓ i18n barrels up to date.');
  }
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) main();
