// i18n lint-exempt list generator (Phase 82 Theme A). The no-hardcoded-string gate
// (`i18next/no-literal-string`, jsx-text-only) is now **default-on** for every
// `.tsx` in `packages/web` + `packages/shell/src` — a file is exempt only if it's on
// the generated `eslint.i18n-exempt.mjs` list. New files are therefore born enforced;
// each migration slice deletes its files from the list, and the count is the phase's
// live progress meter (surfaced by `i18n-validate`).
//
//   node scripts/i18n-exempt.mjs           # regenerate (seed on first run; prune stale after)
//   node scripts/i18n-exempt.mjs --check   # fail if the committed list is out of sync (CI)
//
// The list is **removal-only** after seeding: `sync` never re-adds a file (that would
// silently re-exempt a migrated surface), it only drops entries whose file no longer
// exists (renames/deletes) and keeps the list sorted + deduped. So a brand-new file is
// never auto-exempted — it must either use `t()` or be added by hand with a reason.
// A plain .mjs (node-only, no build) like the sibling validator/extractor/barrels.

import { globSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const ROOT_DIR = join(dirname(fileURLToPath(import.meta.url)), '..');
const EXEMPT_PATH = join(ROOT_DIR, 'eslint.i18n-exempt.mjs');

// The gate covers these globs; a file matching one is enforced unless exempt.
const GATED_GLOBS = ['packages/web/**/*.tsx', 'packages/shell/src/**/*.tsx'];
// Test/story fixtures carry deliberate literal strings for assertions — not user copy.
const NON_COPY = /\.(test|spec|stories)\.tsx$/;
const EXCLUDE_DIRS = /(^|\/)(node_modules|dist|\.next|out|build|build-staging|storybook-static|coverage)(\/|$)/;
// Surfaces Phase 79 already migrated — seeded as enforced (never on the exempt list).
const ALREADY_MIGRATED = new Set([
  'packages/web/components/locale-flag.tsx',
  'packages/web/components/language-switcher.tsx',
  'packages/web/components/auth/sso-buttons.tsx',
  'packages/web/app/(auth)/login/page.tsx',
  'packages/web/app/(main)/settings/settings-sidebar.tsx',
  'packages/web/components/confirm-dialog.tsx',
]);

/** Every `.tsx` the gate would enforce (before applying the exempt list). */
export function gatedCandidates(rootDir = ROOT_DIR) {
  const seen = new Set();
  for (const glob of GATED_GLOBS) {
    for (const rel of globSync(glob, { cwd: rootDir })) {
      const p = rel.split('\\').join('/');
      if (EXCLUDE_DIRS.test(p) || NON_COPY.test(p)) continue;
      seen.add(p);
    }
  }
  return [...seen].sort();
}

/** Parse the committed exempt list (empty if not seeded yet). */
export async function readExempt() {
  if (!existsSync(EXEMPT_PATH)) return [];
  const mod = await import(pathToFileURL(EXEMPT_PATH).href);
  return Array.isArray(mod.I18N_EXEMPT) ? mod.I18N_EXEMPT : [];
}

/** The list `sync` would write: seed on first run, else prune-stale + sort + dedupe. */
export function computeExempt(candidates, current) {
  const candidateSet = new Set(candidates);
  if (current.length === 0) {
    // First run — seed from every unmigrated candidate.
    return candidates.filter((p) => !ALREADY_MIGRATED.has(p));
  }
  // Removal-only: keep current entries that still exist; never auto-add new files.
  return [...new Set(current)].filter((p) => candidateSet.has(p)).sort();
}

function render(list) {
  const body = list.map((p) => `  ${JSON.stringify(p)},`).join('\n');
  return [
    '// GENERATED by scripts/i18n-exempt.mjs — the i18n no-hardcoded-string gate',
    "// (Phase 82 Theme A) is default-on; these files are the exempt tail still awaiting",
    '// migration. Run `node scripts/i18n-exempt.mjs` to prune stale entries; each',
    '// migration slice removes its files from this list. The count is the progress meter.',
    '',
    'export const I18N_EXEMPT = [',
    body,
    '];',
    '',
  ].join('\n');
}

async function main() {
  const check = process.argv.includes('--check');
  const candidates = gatedCandidates();
  const current = await readExempt();
  const next = computeExempt(candidates, current);
  const rendered = render(next);
  const onDisk = existsSync(EXEMPT_PATH) ? readFileSync(EXEMPT_PATH, 'utf8') : null;

  if (check) {
    const stale = current.filter((p) => !candidates.includes(p));
    if (onDisk !== rendered) {
      console.error('✖ eslint.i18n-exempt.mjs is out of sync.');
      if (stale.length) {
        console.error(`  ${stale.length} stale entr(y/ies) (file gone / renamed / now a test):`);
        for (const p of stale) console.error(`    • ${p}`);
      }
      console.error('  Run `node scripts/i18n-exempt.mjs` and commit.');
      process.exit(1);
    }
    console.log(`✓ eslint.i18n-exempt.mjs in sync (${next.length} file(s) exempt).`);
    return;
  }

  writeFileSync(EXEMPT_PATH, rendered);
  const verb = current.length === 0 ? 'seeded' : 'synced';
  console.log(`${verb} eslint.i18n-exempt.mjs — ${next.length} file(s) exempt (of ${candidates.length} gated).`);
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) await main();
